#ifndef TESTER_CORE
#define TESTER_CORE

typedef enum {
	TEST_CMD_GET_TEST_SUITE_COUNT,
	TEST_CMD_GET_TEST_SUITE_NAMES,

	TEST_CMD_GET_TEST_COUNT,
	TEST_CMD_GET_TEST_NAMES,

	TEST_CMD_RUN_TEST,

	TEST_CMD_COUNT,
} TestCommandKind;

#endif
