name: CI
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build_windows:
    name: Windows Build and Test
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        compiler: [cl, clang]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: build_bb
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS_INSTALL=%%i"
          call "%VS_INSTALL%\VC\Auxiliary\Build\vcvarsall.bat" x64
          call scripts/build_bb.bat cl
      - name: Build Compiler
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS_INSTALL=%%i"
          bin/bb.exe build "--cc=${{matrix.compiler}}"
